import Foundation

/// Turns a `ToolchainRecipeDraft` into the overlay `~/<tag>-presets.ini` that `build-toolchain`
/// composes with. The critical invariant: the main section's name must EQUAL the preset name
/// build-toolchain resolves (`presets.py` does a literal dictionary lookup — see `_get_preset`), and
/// it must `mixin-preset` the stock base first so overrides layered after it win.
nonisolated enum ToolchainPresetWriter {
    /// The preset name build-toolchain passes to build-script for this recipe, e.g.
    /// `gistya_buildbot_osx_package,no_test`. Mirrors build-toolchain's name construction exactly.
    static func composedPresetName(prefix: String, flags: Set<ToolchainFlag>) -> String {
        var name = prefix + ToolchainRecipeDraft.bundlePackage
        if flags.contains(.noAssertions) { name += ",no_assertions" }
        if !flags.contains(.runTests) { name += ",no_test" }
        if flags.contains(.useOSRuntime) { name += ",use_os_runtime" }
        if flags.contains(.macosOnly) { name += ",macos_only" }
        return name
    }

    /// The stock base preset (no prefix) the overlay mixes in — must exist in build-presets.ini.
    static func stockBaseName(flags: Set<ToolchainFlag>) -> String {
        composedPresetName(prefix: "", flags: flags)
    }

    /// The overlay `.ini` file contents for a recipe.
    static func overlay(draft: ToolchainRecipeDraft, customPresets: [CustomPresetValue]) -> String {
        var out = "# Generated by SwiftBuilder — overlay preset for `build-toolchain`.\n"
        out += "# Layered under swift/utils/build-presets.ini via --preset-file; overrides win (last wins).\n\n"

        // Emit any custom presets the recipe references (transitively) so build-script can resolve them.
        for custom in referencedCustomPresets(draft: draft, customPresets: customPresets) {
            out += section(name: custom.name, mixins: custom.mixins, optionLines: custom.optionLines)
        }

        let mainName = composedPresetName(prefix: draft.presetPrefix, flags: draft.flags)
        let baseName = stockBaseName(flags: draft.flags)
        out += section(name: mainName, mixins: [baseName] + draft.selectedMixins, optionLines: draft.extraOptions)
        return out
    }

    /// The full command that would run, for preview.
    static func commandPreview(draft: ToolchainRecipeDraft, buildToolchainPath: String, basePresetPath: String, overlayPath: String) -> String {
        var parts = [buildToolchainPath, draft.bundleTag,
                     "--preset-file", basePresetPath,
                     "--preset-file", overlayPath,
                     "--preset-prefix", draft.presetPrefix]
        for flag in draft.flags.sorted(by: { $0.rawValue < $1.rawValue }) {
            parts.append(flag.argument)
        }
        return parts.joined(separator: " ")
    }

    /// The transitive closure of custom presets reachable from the recipe's selected mixins.
    static func referencedCustomPresets(draft: ToolchainRecipeDraft, customPresets: [CustomPresetValue]) -> [CustomPresetValue] {
        let byName = Dictionary(customPresets.map { ($0.name, $0) }, uniquingKeysWith: { a, _ in a })
        var seen = Set<String>()
        var ordered: [CustomPresetValue] = []
        var queue = draft.selectedMixins

        while !queue.isEmpty {
            let name = queue.removeFirst()
            guard !seen.contains(name), let custom = byName[name] else { continue }
            seen.insert(name)
            ordered.append(custom)
            queue.append(contentsOf: custom.mixins)
        }
        return ordered
    }

    private static func section(name: String, mixins: [String], optionLines: [String]) -> String {
        var s = "[preset: \(name)]\n"
        let cleanMixins = mixins.map { $0.trimmingCharacters(in: .whitespaces) }.filter { !$0.isEmpty }
        if !cleanMixins.isEmpty {
            s += "mixin-preset=\n"
            for m in cleanMixins { s += "    \(m)\n" }
        }
        for line in optionLines {
            let clean = line.trimmingCharacters(in: .whitespaces)
            if !clean.isEmpty { s += "\(clean)\n" }
        }
        s += "\n"
        return s
    }
}
